### ISSUE TITLE
Support for IOS & Android Deeplinks

### ISSUE THREAD

**Issue by mangoplane** [Web3Auth/web3auth-unreal-sdk#10]
Hi guys,

Just curious whether you have support for IOS, Android and MacOS yet. Also to what extent is Deeplinking ready to go?

Kind regards.

**Comment by grvgoel81** [comment]
Resolved in PR: https://github.com/Web3Auth/web3auth-unreal-sdk/pull/22 and https://github.com/Web3Auth/web3auth-unreal-sdk/pull/23.
