### ISSUE TITLE
SessionID cached using USaveGame is insecure

### ISSUE THREAD

**Issue by xynanlee** [Web3Auth/web3auth-unreal-sdk#28]
USaveGame despite being a binary object but the properties can still be read in text form, which is probably not a good thing. This issue has been fixed once in issue #8 but it seems to be regressed.

I would like to understand the thought process of caching the sessionID. I would much rather force players to sign in every time the game launch and force sign them out when the app closes (which is most games does).

**Comment by grvgoel81** [comment]
Caching the sessionId so user doesn't have to login again for some time like sessionId max caching time is 7 days. That also can be controlled by dapp with min and max duration ranges from 1-7 days.
