### ISSUE TITLE
Can sessionTimeout use the current authorized session to execute logout?

### ISSUE THREAD

**Issue by xynanlee** [Web3Auth/web3auth-unreal-sdk#29]
The current implementation of sessionTimeout will run AuthorizeSession before logging out. Is it possible for me to cache the session details after I sign in, and directly pass that session details into logout?

I'm trying to implement a logout when the game closes, where I use `UWeb3Auth::Deinitialize()` to call `processLogout`. There is a crash at sessionTimeout's AuthorizeSession callback because the game is closed and the callback is accessing invalid memory. If I can cache the session when I sign in and pass it in for logout, I can eliminate this callback layer and potentially removing the crash.

**Comment by grvgoel81** [comment]
authorizeSession() runs after every successful login not after sessionTimeout(). You can call processLogout() if you want to implement a logout when the game closes.
