### ISSUE TITLE
Logout not working.

### ISSUE THREAD

**Issue by minnakan** [Web3Auth/web3auth-unreal-sdk#3]
When trying to logout the webpage says redirect-uri is not set. I have tried setting the redirect uri to https://www.google.com/ when calling the process logout function but it does not work.

**Comment by minnakan** [comment]
![logout-error2](https://user-images.githubusercontent.com/48321533/189626901-a1ed6dea-98d2-4190-9ee1-5f9ffc91ab94.png)

added screenshot for reference.

**Comment by chaitanyapotti** [comment]
Pls update to the latest version. it should be fixed now

**Comment by minnakan** [comment]
Still looking for a solution. Any help would be appreciated.
Thanks.
