### ISSUE TITLE
Prevent Session Keys being read out in plaintext

### ISSUE THREAD

**Issue by mangoplane** [Web3Auth/web3auth-unreal-sdk#8]
Hi,

Great work with the repo so far. I'm just wondering how you intend to prevent the sensitive keys being read out in plaintext from the save game object. It doesn't seem very secure at the moment, and to that end what measures are you looking to add to improve secure storage.

https://github.com/Web3Auth/web3auth-unreal-sdk/blob/session-management/Plugins/Web3AuthSDK/Source/Web3AuthSDK/Private/KeyStoreUtils.cpp#L13-L16

Maybe what you need is platform specific secure storage, for each platform. E.g. Android Keystore.

Kind regards.

**Comment by metalurgical** [comment]
Persistence to a save game has been disabled.
